### ISSUE TITLE
ERROR TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating#46] opened 2017-05-13 12:26 UTC
`ERROR TypeError: Cannot read property 'classList' of null
    at NavComponent.webpackJsonp.285.NavComponent.closeQueueList (nav.component.ts:83)
    at Object.eval [as handleEvent] (NavComponent.html:1)
    at handleEvent (core.es5.js:11892)
    at callWithDebugContext (core.es5.js:13184)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12772)
    at dispatchEvent (core.es5.js:8792)
    at core.es5.js:10720
    at SafeSubscriber.schedulerFn [as _next] (core.es5.js:3842)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)`

**Steps to reproduce:** 
- open main page http://localhost:4200/leagues
- click somewhere at background
- got an error in console

I suppose that is caused by directive to close queue's modal which isn't visible on this page.

**Comment by tpokora** [comment] 2017-05-15 20:09
Caused by leagueId == null when no league loaded.
Issue fixed by adding check for leaguId.

**Closed** 2017-05-26 13:33 UTC
Labels: bug
